version: '3'
services:
  web:
    image: php:8.1-apache
    container_name: google-scraper-web
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    working_dir: /var/www/html
    command: >
      bash -c "docker-php-ext-install mysqli && apache2-foreground"

  db:
    image: mysql:5.7
    container_name: google-scraper-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scraper
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: google-scraper-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=root

  composer:
    image: composer:latest
    container_name: google-scraper-composer
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["composer"]
    command: ["install"]

  phpunit:
    image: php:8.1-cli
    container_name: google-scraper-phpunit
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["vendor/bin/phpunit"]

volumes:
  db_data:
